#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# environment variables
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"

# scripts that run after cloning repository
install:
  - ps: Install-Product node $env:nodejs_version
  - npm cache clean --force
  - appveyor-retry npm install

build: off # Disable MSBuilds, not related to the regular build process

# to run your custom scripts instead of automatic tests
test_script:
  - set PATH=%PATH%;C:\MinGW\bin;
  - node --version && npm --version && g++ --version && java -version && javac -version
  - cmd: "npm test"

# to disable deployment
deploy: off
